name: fabiomassimo
favicon: null
layout_spectrum: 0.31822
typography_spectrum: 0.34033936238847673
title: fabiomassimo.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#ad7d3c'
    - '#a8a6ab'
    - '#e7cdc5'
  brandStrength: 0.27461159648373723
  lightness: 0.08057682286016643
  saturation: 0.6878646928817034
  rhythmicContrast: 0.9748296954203397
purpose: []
